use format specifications from constants for improved reusability in …
phlib/sms-length pull request #11
Opened 2022-06-21 14:21 UTC by SeifertDaniel

…other packages

2022-06-21 15:04 UTC, chrisminett requested changes
Thanks for your PR! It makes a lot of sense, and looking at this now I'm not sure why these weren't constants in the first place, but I guess that's the benefit of time!

2022-06-21 15:04 UTC, chrisminett commented on src/SmsLength.php
> +    const FORMAT_7BIT = '7-bit';
As this package is targeting newer(ish) versions of PHP, please add visibility to the constants.
They need to be public, so I'd make them the very first constants in the file, following the format that's used for other public constants. Also, `FORMAT` isn't quite accurate, as it's the encoding that's being defined, so I think these would be better as `ENCODING_7BIT` etc.

2022-06-22 08:16 UTC, SeifertDaniel commented
You are right, of course. The old style code came from the fact that I developed the PR for version 1 and then migrated it to version 2.

2022-06-26 04:13 UTC, chrisminett approved these changes

2022-06-26 04:17 UTC, merged